package domin;
// Generated 2016-2-18 13:11:28 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Classes generated by hbm2java
 */
public class Classes implements java.io.Serializable {

	private Integer classId;
	private String academy;
	private String major;
	private Set<Student> students = new HashSet<Student>(0);

	public Classes() {
	}

	public Classes(Integer classId, String academy, String major) {
		this.classId = classId;
		this.academy = academy;
		this.major = major;
	}

	public Classes(Integer classId, String academy, String major, Set<Student> students) {
		this.classId = classId;
		this.academy = academy;
		this.major = major;
		this.students = students;
	}

	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public String getAcademy() {
		return this.academy;
	}

	public void setAcademy(String academy) {
		this.academy = academy;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
