package domin;
// Generated 2016-2-18 13:11:28 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private Integer courseId;
	private String courseName;
	private Integer credit;
	private Integer classHour;
	private Set<Teacher> teachers = new HashSet<Teacher>(0);
	private Set<Studentcourse> studentcourses = new HashSet<Studentcourse>(0);

	public Course() {
	}

	public Course(Integer courseId, String courseName, Integer credit, Integer classHour) {
		this.courseId = courseId;
		this.courseName = courseName;
		this.credit = credit;
		this.classHour = classHour;
	}

	public Course(Integer courseId, String courseName, Integer credit, Integer classHour, Set<Teacher> teachers, Set<Studentcourse> studentcourses) {
		this.courseId = courseId;
		this.courseName = courseName;
		this.credit = credit;
		this.classHour = classHour;
		this.teachers = teachers;
		this.studentcourses = studentcourses;
	}

	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public Integer getCredit() {
		return this.credit;
	}

	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	public Integer getClassHour() {
		return this.classHour;
	}

	public void setClassHour(Integer classHour) {
		this.classHour = classHour;
	}

	public Set<Teacher> getTeachers() {
		return this.teachers;
	}

	public void setTeachers(Set<Teacher> teachers) {
		this.teachers = teachers;
	}

	public Set<Studentcourse> getStudentcourses() {
		return this.studentcourses;
	}

	public void setStudentcourses(Set<Studentcourse> studentcourses) {
		this.studentcourses = studentcourses;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((courseId == null) ? 0 : courseId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Course other = (Course) obj;
		if (courseId == null) {
			if (other.courseId != null)
				return false;
		} else if (!courseId.equals(other.courseId))
			return false;
		return true;
	}

}
